---
-
  hosts: <group>  
     
  tasks:
    - name: Remove Datadog Agent 
      yum: 
        name: datadog-agent
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove the /etc/datadog-agent directory on Redhat
      ansible.builtin.file:
        path: /etc/datadog-agent
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Datadog Agent 
      apt: 
        name: datadog-agent
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"


    - name: Remove the /etc/datadog-agent directory on Rocky Linux
      ansible.builtin.file:
        path: /etc/datadog-agent
        state: absent
      when: ansible_os_family == "Rocky"

    - name: Remove the /opt/datadog-agent directory
      ansible.builtin.file:
        path: /opt/datadog-agent
        state: absent

...
